version: '3.8'

services:
  webui:
    build: .
    runtime: nvidia  # Use NVIDIA runtime
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      # Optional: If you have model weights stored locally, mount them here
      # - ./models:/app/models
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]